version: "3.7"

services:
db:
image: postgres:13-alpine
container_name: database
restart: always
enviornment:
  POSTGRES_BD: postgres
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: my-weak-password
volumes:
  - /var/lib/postgresql/data
ports:
  - 5432:54432
