version: "3.7"
services:


db:
image: postgres:13-alpine
container_name: database
restart: always
enviornment:
  POSTGRES_BD: postgres
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: my-weak-password
volumes:
  - /var/lib/postgresql/data
ports:
  - 5432:54432



pgadmin:
  image: dpage/pgadmin4
  container_name: pgAdmin
  restart: always
  enviornment:
  PGADMIN_EMAIL: admin@nestjs.com
  PGADMIN_PASSWORD: my-weak-password
  PGADMIN_LISTEN_PORT: 80
  PORTS:
    - 8080:80
  volumes:
    - /var/lib/pgadmin
  depends_on:
    - db
